[package]
name = "dw-systest"
version = "0.1.1"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[dependencies]
dw-sys = { path = "../dw-sys" }
libc = "0.2"

[build-dependencies]
#ctest2 = "^0.3.1"
ctest2 = { "git" = "https://github.com/GreenBeard/ctest2" }
